// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpLthurr57O4Use66ZN0te0lAEuTEF3SE',
    appId: '1:1080679911054:web:5bbedab1b6ca34df8dc3df',
    messagingSenderId: '1080679911054',
    projectId: 'jmks48',
    authDomain: 'jmks48.firebaseapp.com',
    databaseURL: 'https://jmks48-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'jmks48.firebasestorage.app',
    measurementId: 'G-GGMFYSCK0T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSJihsZ8Mz-BM2bwL4b8Hw4dWs3a4BQlA',
    appId: '1:1080679911054:android:41679a4d3738ab528dc3df',
    messagingSenderId: '1080679911054',
    projectId: 'jmks48',
    databaseURL: 'https://jmks48-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'jmks48.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJXgDn7G2QkcuLWuIKgsYMmkJQvpIn62Y',
    appId: '1:1080679911054:ios:dbeda737843452488dc3df',
    messagingSenderId: '1080679911054',
    projectId: 'jmks48',
    databaseURL: 'https://jmks48-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'jmks48.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJXgDn7G2QkcuLWuIKgsYMmkJQvpIn62Y',
    appId: '1:1080679911054:ios:dbeda737843452488dc3df',
    messagingSenderId: '1080679911054',
    projectId: 'jmks48',
    databaseURL: 'https://jmks48-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'jmks48.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpLthurr57O4Use66ZN0te0lAEuTEF3SE',
    appId: '1:1080679911054:web:12f28b39eacb0d568dc3df',
    messagingSenderId: '1080679911054',
    projectId: 'jmks48',
    authDomain: 'jmks48.firebaseapp.com',
    databaseURL: 'https://jmks48-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'jmks48.firebasestorage.app',
    measurementId: 'G-Z969LBJCWC',
  );
}
