// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJsPiPbNX330aa-qEMR7-5KvHDDdNFd9Q',
    appId: '1:911015308233:web:7d6d66889f917db7c4d618',
    messagingSenderId: '911015308233',
    projectId: 'fel-apps',
    authDomain: 'fel-apps.firebaseapp.com',
    storageBucket: 'fel-apps.firebasestorage.app',
    measurementId: 'G-RLCD9HXH04',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjvxlp3OYRRg9ic4u-pshp0OK9ZgXFNPw',
    appId: '1:911015308233:android:35db9030570338c2c4d618',
    messagingSenderId: '911015308233',
    projectId: 'fel-apps',
    storageBucket: 'fel-apps.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJsPiPbNX330aa-qEMR7-5KvHDDdNFd9Q',
    appId: '1:911015308233:web:bb5d1abb4de6bf31c4d618',
    messagingSenderId: '911015308233',
    projectId: 'fel-apps',
    authDomain: 'fel-apps.firebaseapp.com',
    storageBucket: 'fel-apps.firebasestorage.app',
    measurementId: 'G-4EZ06GPHJM',
  );
  
}
